import Navbar2 from "@/components/Navbar2"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar2 />
        {children}</body>
    </html>
  )
}
